name: Newman-Identity-Service-Run

on:
  push:
   branches:
     - master
   paths:
      - 'AWS-GTSIdentityServices.postman_collection.json'
           

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
        #apiKey: ${{ secrets.postmanApiKey }}
         collection: AWS-GTSIdentityServices.postman_collection.json
         reporters: cli

      #- name: Output summary to console
        #run: echo ${{ steps.run-api-tests.outputs.summary }}
