name: Newman-Identity-Service-Run

on:
  push:
   branches:
     - master
   paths:
      - 'AWS-GTSPersonalDetails.json'
           

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          #collection: postman-collection.json
      - run: npm install -g newman
      - run: newman run AWS-GTSPersonalDetails.json -k

 
 

